#!/usr/bin/env bash

. "$(dirname "$BASH_SOURCE")/lib/bridge-util.sh"

{

echo ""
echo "Running open-parent-in-terminal in directory $(pwd)"
echo ""

open-in-terminal

} 2>&1 | tee -a "$(get_log_path open-parent-in-terminal)"
